# Generated by Django 6.0.4 on 2026-04-22 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=12, unique=True, verbose_name='Token')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('pet_name', models.CharField(blank=True, max_length=100, verbose_name='Nome do Pet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_tokens', to='core.petshop')),
            ],
            options={
                'verbose_name': 'Token de Acesso',
                'indexes': [models.Index(fields=['pet_shop'], name='publico_cli_pet_sho_4a5812_idx')],
            },
        ),
    ]
