# Generated by Django 6.0.4 on 2026-04-22 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('type', models.CharField(choices=[('vacina', 'Vacina'), ('vermifugo', 'Vermífugo'), ('alergia', 'Alergia'), ('doenca', 'Doença'), ('cirurgia', 'Cirurgia'), ('medicamento', 'Medicamento'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('next_due', models.DateField(blank=True, null=True, verbose_name='Próximo Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='cadastro.pet')),
                ('pet_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='core.petshop')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['pet_shop'], name='prontuario__pet_sho_4cc9f4_idx')],
            },
        ),
    ]
