# Generated by Django 6.0.4 on 2026-04-22 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pet_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.petshop'),
        ),
        migrations.AddField(
            model_name='service',
            name='pet_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.petshop'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='agenda.service'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['pet_shop'], name='agenda_appo_pet_sho_753b8c_idx'),
        ),
    ]
