# Generated by Django 6.0.4 on 2026-04-22 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('method', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_credito', 'Cartão Crédito'), ('cartao_debito', 'Cartão Débito')], max_length=20, verbose_name='Método')),
                ('status', models.CharField(choices=[('paid', 'Pago'), ('pending', 'Pendente'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='agenda.appointment')),
                ('pet_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.petshop')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pet_shop'], name='financeiro__pet_sho_455af9_idx')],
            },
        ),
    ]
