# Generated by Django 6.0.4 on 2026-04-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_visits', models.PositiveIntegerField(default=10, verbose_name='Visitas para desconto')),
                ('visits_count', models.PositiveIntegerField(default=0, verbose_name='Visitas')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='Resgatado em')),
            ],
            options={
                'verbose_name': 'Cartão Fidelidade',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('species', models.CharField(choices=[('dog', 'Cachorro'), ('cat', 'Gato'), ('bird', 'Pássaro'), ('rabbit', 'Coelho'), ('hamster', 'Hamster'), ('fish', 'Peixe'), ('reptile', 'Réptil'), ('other', 'Outro')], default='dog', max_length=20, verbose_name='Espécie')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Raça')),
                ('size', models.CharField(blank=True, choices=[('small', 'Pequeno'), ('medium', 'Médio'), ('large', 'Grande'), ('giant', 'Gigante')], max_length=20, verbose_name='Porte')),
                ('gender', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, verbose_name='Sexo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Cor')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tutor',
                'ordering': ['name'],
            },
        ),
    ]
