# Generated by Django 6.0.4 on 2026-04-22 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltycard',
            name='pet_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.petshop'),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.petshop'),
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_card', to='cadastro.pet'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='pet_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.petshop'),
        ),
        migrations.AddField(
            model_name='pet',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='cadastro.tutor'),
        ),
        migrations.AddIndex(
            model_name='tutor',
            index=models.Index(fields=['pet_shop'], name='cadastro_tu_pet_sho_41048b_idx'),
        ),
        migrations.AddConstraint(
            model_name='tutor',
            constraint=models.UniqueConstraint(fields=('pet_shop', 'email'), name='unique_tutor_email_per_petshop'),
        ),
    ]
